
services:
  tms.api:
    image: tms.api
    build:
      context: .
      dockerfile: TMS.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  tms.cache:
    image: redis:6.0
    restart : always
    ports:
      - "6379:6379"
  
  tms.db:
    image: postgres:latest
    restart: always
    container_name: tms.db
    environment:
      POSTGRES_USER: "Mmo2ze"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tms"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  
  
  tms.mq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"